name: development
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.11.0
  lottie: ^2.7.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  anim_search_bar: ^2.0.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banners/
    - assets/images/icons/
    - assets/images/logo/

  fonts:
    - family: KlasikRegular
      fonts:
        - asset: assets/fonts/klasik_regular.otf
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/manrope_regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
